
[package]
name = "psql_parser"
version = "0.0.1"
edition.workspace = true

[dependencies]
psql_syntax = { workspace = true }
psql_factory = { workspace = true }

biome_parser = { workspace = true }
biome_rowan = { workspace = true }
biome_unicode_table = { workspace = true }

